### ISSUE TITLE
Could not find OpenGL

### ISSUE THREAD

**Issue by YBurakD** [mbotsch/FastProjectiveSkinning#2]
Hi. I am trying to build this repo in Ubuntu 18.04 LTS but I am getting the following error:

![image](https://user-images.githubusercontent.com/32135008/107038351-6ecfc980-67cd-11eb-9efb-c4b360309077.png)

Before this I got "The RandR library and headers were not found." error and to fix it I installed xorg-dev and libglu1-mesa-dev. After these, I got the aforementioned error.

**Comment by mbotsch** [comment]
It seems that you don't have all the required OpenGL packages installed. Please try these:
```
sudo apt-get install libx11-dev libxmu-dev libxi-dev libgl-dev
```
